name: Proxy Updater

on:
  schedule:
    - cron: '0 */4 * * *'
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Scrape Proxies
        continue-on-error: true
        run: |
          rm -rf anonymous-proxylist proxylist
          chmod +x src/scraper.sh
          sh src/scraper.sh

      - name: Push Updated Proxies
        continue-on-error: true
        run: |
          git config --local user.email ${{ secrets.GIT_EMAIL }}
          git config --local user.name ${{ secrets.GIT_NAME }}
          git add proxylist anonymous-proxylist
          git commit -am "Updated Proxies : $(TZ='Asia/Dhaka' date)"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}

